name: CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, gd
          tools: composer:v2
          coverage: none

      - name: Debug Environment
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Configure Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install Dependencies
        run: |
          # Check if composer.json exists in the expected location
          if [ -f "composer.json" ]; then
            echo "Found composer.json in root directory"
            composer install -v
          elif [ -f "app/composer.json" ]; then
            echo "Found composer.json in app directory"
            cd app
            composer install -v
          else
            echo "Could not find composer.json in root or app directory"
            find . -name "composer.json"
            exit 1
          fi
        env:
          COMPOSER_PROCESS_TIMEOUT: 0
          COMPOSER_NO_INTERACTION: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install JS Dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
          elif [ -f "app/package.json" ]; then
            cd app
            npm ci
          else
            echo "Could not find package.json"
            exit 1
          fi

      - name: Build frontend
        run: |
          if [ -f "package.json" ]; then
            npm run build
          elif [ -f "app/package.json" ]; then
            cd app
            npm run build
          else
            echo "Could not find package.json"
            exit 1
          fi

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/proxmox/portfolio
            git -C app pull origin master
            docker-compose exec -T app composer install --no-dev --optimize-autoloader
            docker-compose exec -T app npm install
            docker-compose exec -T app npm run build
            docker-compose exec -T app php bin/console doctrine:migrations:migrate --no-interaction
            docker-compose exec -T app php bin/console cache:clear